name: Build APK with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build APK with Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        outputs: type=local,dest=./output
        tags: kivy-app:latest
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kabab-inventory-apk
        path: output/*.apk
